FROM golang:1.21-alpine

WORKDIR /app

COPY . /app
ENV HOSTNAME=live_dev_container

RUN go mod tidy
RUN go mod download

# Install Reflex for development
RUN go install github.com/cespare/reflex@latest

EXPOSE 8080

CMD reflex -r '\.go$$' -s go run cmd/main.go